# Generated by Django 2.2.1 on 2019-06-13 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190613_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='bike_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartid', to='cart.Bike'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartuser', to='cart.Bike'),
        ),
    ]
