# Generated by Django 2.2.1 on 2019-06-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190613_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='id_bike',
            new_name='bike_id',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='id_user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='bike_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cartid', to='cart.Bike'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cartuser', to='cart.Bike'),
        ),
    ]
