# Generated by Django 2.2.1 on 2019-06-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20190613_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='bike_id',
            new_name='id_bike',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='user_id',
            new_name='id_user',
        ),
    ]
