# Generated by Django 2.2.1 on 2019-06-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20190613_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='id_bike',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='id_user',
            new_name='user',
        ),
    ]
