# Generated by Django 2.2.1 on 2019-06-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20190613_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='bike',
            new_name='id_bike',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='user',
            new_name='id_user',
        ),
    ]
