# Generated by Django 2.2.1 on 2019-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20190613_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
