# Generated by Django 2.2.1 on 2019-06-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_bike_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='id_bike',
            new_name='bike_id',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='id_user',
            new_name='user_id',
        ),
    ]
