# Generated by Django 2.2.1 on 2019-06-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20190613_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
