# Generated by Django 2.2.1 on 2019-06-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20190615_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='bike_id',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='user_id',
        ),
    ]
