# Generated by Django 2.2.1 on 2019-06-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20190616_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='name',
            field=models.CharField(default='new bike', max_length=150),
        ),
    ]
