# Generated by Django 2.2.1 on 2019-08-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_bike_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
