# Generated by Django 2.2.1 on 2019-08-03 08:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20190801_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
    ]
