# Generated by Django 2.2.1 on 2019-08-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_auto_20190803_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
