# Generated by Django 2.2.1 on 2019-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=120),
        ),
    ]
