# Generated by Django 2.2.1 on 2019-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20190805_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Bhaktapur-5 , Ghattaghar', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Bhaktapur', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='nitesh', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='pantha', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.CharField(default='nitesh@123', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='province_no 1', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='nitesh_pantha', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.IntegerField(default='001'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
