# Generated by Django 2.2.1 on 2019-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20190805_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Email',
            field=models.EmailField(default='niteshraz619@gmail.com', max_length=250, verbose_name='Email'),
        ),
    ]
